[phases.setup]
nixPkgs = ['python311', 'nodejs_18', 'postgresql']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'cd agente_digital_ui && npm install'
]

[phases.build]
cmds = [
    'cd agente_digital_ui && npm run build'
]

[start]
cmd = 'cd agente_digital_api && gunicorn -w 4 -b 0.0.0.0:$PORT app:create_app()'